version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:8.11.3
    steps:
      - checkout
      - run: npm install
      - run: npm run test
      - run: npm run build
      - persist_to_workspace:
          root: .
          paths:
           - .ansible

  deploy:
    docker:
      - image: circleci/python:3.7.7
    steps:
      - attach_workspace:
          at: .
      - run: pip3 install ansible boto boto3
      - run: echo $SSH_PRIVATE_KEY | sed 's/<CRLF>/\n/g' > newkey2.pem
      - run: chmod 400 newkey2.pem
      - run: export ANSIBLE_HOST_KEY_CHECKING=False
      - run: ANSIBLE_HOST_KEY_CHECKING=False ansible-playbook .ansible/ec2_deploy.yml --user ubuntu --key-file newkey2.pem

workflows:
  version: 2.1
  build:
    jobs:
      - build
      - deploy:
         requires:
          - build
         filters:
           branches:
              only: master